# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

include: ['_pages','_team']


# Site settings
title: RegattaHub
author: Shomberg Systems
copyright_date: 2016
email: contact@regattahub.com
description: > # this means to ignore newlines until "baseurl:"
    RegattaHub is a simple program for building and running sailing races.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://regattahub.com" # the base hostname & protocol for your site
twitter_username: 
github_username: 
linkedin_username: 
google_plus_username: 
facebook_username:    
dribbble_username:
mailchimp_listid: 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-86719708-1
#disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
